/* Loads the data and the modules the way the page does; returns TG. */
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
const TG = require("../js/tailo.js");
require("../js/sandhi.js");
require("../js/dict.js");
const read = (f) => JSON.parse(fs.readFileSync(path.join(root, "data", f), "utf8"));
TG.dict.init(read("dict.json"));
TG.dict.set("huayu", read("huayu.json"));
TG.dict.set("chars", read("chars.json"));
TG.dict.set("examples", read("examples.json"));
TG.dict.set("daily", read("daily.json"));
TG.dict.set("synonyms", read("synonyms.json"));
TG.dict.set("audio", read("audio.json"));
TG.dict.set("proverbKw", read("proverb_kw.json"));
require("../js/convert.js");
require("../js/proverb.js");
require("../js/audio.js");
TG.proverb.init();
module.exports = TG;
